### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by nerdalertdk** [BAROD/Koth_Kavala#8]
Hi could find an email

Are you still working on this project ? If yes I might be able to help with an test server ? 
Just look through the code looks really promising :)

**Comment by BAROD** [comment]
sry that I don't replied to your message,
the last couple of days were a bit stressful for me,

and a test server is not needed..

**Comment by nerdalertdk** [comment]
That okay, and btw. damnn the "framework" is off the chain.
If you need any help let me, know, my "Arma code skills" is not as god as yours, but will help with what I can

btw. are you playing to spawn mission buildings/bases/objects/markers from the server ?
think this will make multi town missions easier ?

**Comment by BAROD** [comment]
yeah maybe later with a voting system...

**Comment by nerdalertdk** [comment]
sounds cool :)

will keep an eye on you github :)
